[project]
name = "dqn-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.0.0",
    "matplotlib>=3.9.2",
    "mlflow>=2.17.2",
    "numpy>=2.1.2",
    "pyyaml>=6.0.2",
    "torch>=2.5.1",
]
